baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs = false
title = "Hugo学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
	# General information
	author = "敖小剑"
	keywords = "hugo,学习笔记,敖小剑,主题"
	description = "Hugo是由Go语言实现的静态网站生成器。这份hugo学习笔记，记录hugo的基本使用和常用技巧，还有推荐的hugo主题。"
	copyright = "版权所有，转载请注明出处"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/skyao/learning-hugo"
	
	version = ""
	logo = "images/logo.png"
	favicon = ""
	
	permalink = "#"
	
	# Custom assets
	custom_css = []
	custom_js  = []
	
	# Syntax highlighting theme
	highlight_css  = ""
	
	[params.palette]
		primary = "red"
		accent  = "teal"
	
	[params.font]
		text = "Ubuntu"
		code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"

[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 100

[[menu.main]]
	name   = "安装"
	identifier = "installation"
	url    = "/installation/"
	weight = 200

[[menu.main]]
	name   = "主题"
	identifier = "theme"
	url    = "/theme/"
	weight = 300

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


